// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGMLL0m_VcarmjbeUOiaz8g8Abi4THq2s',
    appId: '1:457304265367:web:4b94a4bb5c6bb812278fd2',
    messagingSenderId: '457304265367',
    projectId: 'malepa-cf855',
    authDomain: 'malepa-cf855.firebaseapp.com',
    databaseURL: 'https://malepa-cf855-default-rtdb.firebaseio.com',
    storageBucket: 'malepa-cf855.appspot.com',
    measurementId: 'G-WPYQNFTNMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjHcK2w5-sVgpoLe8En72XA2yHsIVh7Vc',
    appId: '1:457304265367:android:64bf63b2a5065096278fd2',
    messagingSenderId: '457304265367',
    projectId: 'malepa-cf855',
    databaseURL: 'https://malepa-cf855-default-rtdb.firebaseio.com',
    storageBucket: 'malepa-cf855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-HaJ-uo61icUWnRuNaHf1G9ex0c4-96Q',
    appId: '1:457304265367:ios:1d565fc1e978b5e3278fd2',
    messagingSenderId: '457304265367',
    projectId: 'malepa-cf855',
    databaseURL: 'https://malepa-cf855-default-rtdb.firebaseio.com',
    storageBucket: 'malepa-cf855.appspot.com',
    iosBundleId: 'com.example.malepaRedesign',
  );
}
