name: Build and Deploy

on:
  push:
    branches:
      - master # Trigger the workflow on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3" # Specify the Flutter version you want to use

      - name: Install dependencies
        run: flutter pub get

      - name: Build web files
        run: flutter build web --base-href /

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web/
